### ISSUE TITLE
UITabBarController approach

### ISSUE THREAD

**Issue by ghost** [andrei-blaj/appstoreclone#1]
If I added Navigation Controller from Appdelegate 
it gives an error that "Could not cast value of type 'appstoreclone.TabBarController' (0x10bdd5e80) to 'appstoreclone.TodayView' (0x10bdd5c20)."
in CardTransitionManager

**Comment by andrei-blaj** [comment]
Hi!

If you decide to go for the TabBarController approach to things so it would look exactly like the App Store app you need account for this change in your CardTransitionManager.swift

```
let fromView = transitionContext.viewController(forKey: .from)
let toView = transitionContext.viewController(forKey: .to)

guard let cardView = (transition == .presentation) ? (fromView as! TodayView).selectedCellCardView() :
                                                     (toView as! TodayView).selectedCellCardView()
else { return }
```

Before the **fromView** was simply a **UIViewController** because we did not use a **UITabBarController**.
But now the **fromView** (or toView, depending on whether you are presenting or dismissing) will be of type **UITabBarController**.

To solve this we need to cast the **fromView** as a **UITabBarController** and get the **selectedViewController** from it and cast that as a **TodayView**.

`((fromView as? UITabBarController)?.selectedViewController as? TodayView)?.selectedCellCardView()`

So now the code will look like this:

```
guard let cardView = (transition == .presentation) ? 
          ((fromView as? UITabBarController)?.selectedViewController as? TodayView)?.selectedCellCardView() :
          ((toView as? UITabBarController)?.selectedViewController as? TodayView)?.selectedCellCardView()
else { return }
```

Hope this helps!
